export const SET_LOADED = 'SET_LOADED'
export const ADD_BURGER_CART = 'ADD_BURGER_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const ADD_LOCAL_ITEM = 'ADD_LOCAL_ITEM'
export const REMOVE_LOCAL_ITEM = 'REMOVE_LOCAL_ITEM'
export const AUTH_ACTION = 'AUTH_ACTION'
export const OPEN_ACTION = 'OPEN_ACTION'
export const SET_BURGERS_ALL = 'SET_BURGERS_ALL'
export const SET_BURGERS = 'SET_BURGERS'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_OPEN_VACANCY = 'SET_OPEN_VACANCY'
export const SET_MESSAGE = 'SET_MESSAGE'







